name: Build and Release Wheels

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:

  build-linux:
    name: Build Linux Wheels
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    container:
      image: "nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04"

    steps:
    - uses: actions/checkout@v3

    - name: Install Python ${{ matrix.python-version }} and GCC 10
      run: |
        apt update
        apt install -y software-properties-common
        add-apt-repository -y ppa:deadsnakes/ppa
        add-apt-repository ppa:ubuntu-toolchain-r/test -y
        apt update
        apt install -y gcc-10 g++-10 \
                       python${{ matrix.python-version }} \
                       python${{ matrix.python-version }}-distutils \
                       python${{ matrix.python-version }}-dev \
                       curl ninja-build
        curl -sS https://bootstrap.pypa.io/get-pip.py | python${{ matrix.python-version }}

        # Set GCC 10 as default
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

    - name: Check GCC version
      run: g++ --version

    - name: Install build tools
      run: python${{ matrix.python-version }} -m pip install build numpy

    - name: Clean dist
      run: rm -rf dist

    - name: Build CPU Wheel
      run: python${{ matrix.python-version }} -m build --wheel --outdir dist/cpu

    - name: Build GPU Wheel
      env:
        TORCH_CUDA_ARCH_LIST: "7.0;7.5;8.0;8.6;8.9;9.0"
      run: RSPMM_WITH_CUDA=1 python${{ matrix.python-version }} -m build --wheel --outdir dist/gpu

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/cpu/*.whl
          dist/gpu/*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-macos:
    name: Build macOS Wheels
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build numpy

    - name: Clean dist
      run: rm -rf dist

    - name: Build CPU Wheel (macOS)
      run: python -m build --wheel --outdir dist/cpu

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/cpu/*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-index:
    name: Update GitHub Pages Index
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Generate index.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install requests
        python generate_index.py

    - name: Commit and Push index.html
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        git add docs/index.html
        git commit -m "🤖 Update index.html for wheels [skip ci]" || echo "No changes"
        git push
